### ISSUE TITLE
Error: Cannot find module 'inquirer'

### ISSUE THREAD

**Issue by blundell** [intel-android/androidhub#42]
Hi,

The inquirer module isn't bundle with your module so you get the error—in the title—when running the `new` task.

`npm install inquirer` in your module directory is enough to fix the problem but this extra step isn't obvious to everyone.

```
> node ./scripts/new-author.js

module.js:338
    throw err;
    ^

Error: Cannot find module 'inquirer'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/foo/androidhub/scripts/new-author.js:13:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/bin/npm" "run" "new"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! intel-android-hub@0.0.1 new: `node ./scripts/new-author.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the intel-android-hub@0.0.1 new script 'node ./scripts/new-author.js'.
npm ERR! This is most likely a problem with the intel-android-hub package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/new-author.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls intel-android-hub
npm ERR! There is likely additional logging output above.
```

**Comment by blundell** [comment]
and then I get the same problem with `request`

```
> node ./scripts/new-author.js

module.js:338
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/foo/androidhub/scripts/new-author.js:16:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
```

**Comment by blundell** [comment]
and finally `js-yaml`

```
> node ./scripts/new-author.js

module.js:338
    throw err;
    ^

Error: Cannot find module 'js-yaml'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/foo/androidhub/scripts/new-author.js:17:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
```

**Comment by blundell** [comment]
Solution:

`npm install inquirer `
`npm install request`
`npm install js-yaml`

but you should fix the script :)

**Comment by intel-android** [comment]
@blundell Thanks for reaching out. All of these modules are all in the package.json file, and when I delete my node_modules dir and then run `npm install` they all seem to come in properly.

**Comment by blundell** [comment]
Right, I was following these instructions here: https://github.com/intel-android/androidhub/blob/master/authors_readme.md and running `npm install` was not mentioned.
